:: Autogenerated by Dynamo 2.0.0 alpha 3    2022-06-19 12:36:35
:: The CD command before DEL works around issues with spaces in the path (cmd is dumb)

:: Restore oTestLive Draw_0
xcopy "A:\GitHub repos\Mine\Dynamo\DynamoExample/objects/otestlive/Draw_0.backup" "A:\GitHub repos\Mine\Dynamo\DynamoExample/objects/otestlive/Draw_0.gml" /f /c /y
cd "A:\GitHub repos\Mine\Dynamo\DynamoExample/objects/otestlive"
del /q "Draw_0.backup"

