/// Autogenerated by Dynamo 2.0.0 alpha 3    2022-06-19 12:36:35

function __DynamoExpressionData()
{
    __DynamoExpressionFileWatch("oTestLive Draw_0", "__dynamo_oTestLive_Draw_0_var", "objects/otestlive/Draw_0.gml", "bcdeb32e58ea540914abf147dcad3881");
    
    global.__dynamoExpressionDict = {
        __dynamo_oTestLive_Draw_0_var0: __DynamoExpressionCompile("310 + 64"),
        __dynamo_oTestLive_Draw_0_var1: __DynamoExpressionCompile("\"hello world!!\""),
    };
}