/// Dynamo 2.0.0 alpha 3 2022-05-28
/// Autogenerated file 2022-06-17 21:33:45

global.__dynamoGMLArray = [
    "objects/oTestLive/Draw_0.gml",
];

global.__dynamoVariableLookup = {
    "__Dynamo_oTestLive_t8_n0_var0": __DynamoExpressionCompile("310 + 64"),
    "__Dynamo_oTestLive_t8_n0_var1": __DynamoExpressionCompile("\"hello world\""),
};