/// @param directory

function __DynamoSaveOutRestoreBatchFile(_directory)
{
    var _batchPath = _directory + "dynamoRestore.bat";
    var _buffer = buffer_create(1024, buffer_grow, 1);
    
    buffer_write(_buffer, buffer_text, ":: Autogenerated by Dynamo ");
    buffer_write(_buffer, buffer_text, __DYNAMO_VERSION);
    buffer_write(_buffer, buffer_text, "\r\n\r\n");
    
    var _i = 0;
    repeat(array_length(global.__dynamoRestoreArray))
    {
        var _data = global.__dynamoRestoreArray[_i];
        var _name = _data.__name;
        var _originalPath = _data.__originalPath;
        var _backupPath = _data.__backupPath;
        
        buffer_write(_buffer, buffer_text, ":: Restore ");
        buffer_write(_buffer, buffer_text, _name);
        buffer_write(_buffer, buffer_text, "\r\nxcopy \"");
        buffer_write(_buffer, buffer_text, _backupPath);
        buffer_write(_buffer, buffer_text, "\" \"");
        buffer_write(_buffer, buffer_text, _originalPath);
        buffer_write(_buffer, buffer_text, "\" /f /c /y\r\ncd \"");
        buffer_write(_buffer, buffer_text, filename_dir(_backupPath));
        buffer_write(_buffer, buffer_text, "\"\r\ndel /q \"");
        buffer_write(_buffer, buffer_text, filename_name(_backupPath));
        buffer_write(_buffer, buffer_text, "\"\r\n\r\n");
        
        ++_i;
    }
    
    buffer_save(_buffer, _batchPath);
    buffer_delete(_buffer);
}