/// @param directory

function __DynamoVariableLookupExport(_directory)
{
    var _path = _directory + "scripts/__dynamovariablelookupdata/__dynamovariablelookupdata.gml";
    if (!file_exists(_path))
    {
        __DynamoError("Could not export Dynamo variables to \"", _path, "\"\nPlease check that this script exists in your project");
        return;
    }
    
    __DynamoTrace("Exporting Dynamo variable expressions to \"", _path, "\"");
    
    var _buffer = buffer_create(1024, buffer_grow, 1);
    
    buffer_write(_buffer, buffer_text, "//Autogenerated file\n");
    buffer_write(_buffer, buffer_text, "\n");
    buffer_write(_buffer, buffer_text, "global.__dynamoVariableLookup = {\n");
    
    var _nameArray = variable_struct_get_names(global.__dynamoVariableLookup);
    array_sort(_nameArray, true); //Prettify the output a bit
    
    var _i = 0;
    repeat(array_length(_nameArray))
    {
        var _name  = _nameArray[_i];
        var _value = global.__dynamoVariableLookup[$ _name];
        
        //Sanitize!
        _name  = string_replace_all(_name,  "\"", "\\\"");
        _value = string_replace_all(_value, "\"", "\\\"");
        
        buffer_write(_buffer, buffer_text, "    ");
        buffer_write(_buffer, buffer_text, "\""); //We wrap the variable identifier in quote marks just in case a space sneaks in
        buffer_write(_buffer, buffer_text, _name);
        buffer_write(_buffer, buffer_text, "\": \"");
        buffer_write(_buffer, buffer_text, _value);
        buffer_write(_buffer, buffer_text, "\",\n");
        
        ++_i;
    }
    
    buffer_write(_buffer, buffer_text, "};");
    
    buffer_save(_buffer, _path);
    buffer_delete(_buffer);
    
    __DynamoTrace(array_length(_nameArray), " expressions were exported");
}