/// @param directory

function __DynamoVariableDataExport(_directory)
{
    var _path = _directory + "scripts/__dynamovariablelookupdata/__dynamovariablelookupdata.gml";
    if (!file_exists(_path))
    {
        __DynamoError("Could not export Dynamo variables to \"", _path, "\"\nPlease check that this script exists in your project");
        return;
    }
    
    __DynamoTrace("Exporting Dynamo variable expressions and trackable GML files to \"", _path, "\"");
    
    
    
    //File header
    var _buffer = buffer_create(1024, buffer_grow, 1);
    buffer_write(_buffer, buffer_text, "/// Dynamo " + __DYNAMO_VERSION + " " + __DYNAMO_DATE + "\n");
    buffer_write(_buffer, buffer_text, "/// Autogenerated file " + string(date_datetime_string(date_current_datetime())) + "\n");
    buffer_write(_buffer, buffer_text, "\n");
    
    
    
    //Write the trackable GML files first
    buffer_write(_buffer, buffer_text, "global.__dynamoGMLArray = [\n");
    
    var _nameArray = array_create(array_length(global.__dynamoGMLArray));
    var _i = 0;
    repeat(array_length(global.__dynamoGMLArray))
    {
        _nameArray[@ _i] = global.__dynamoGMLArray[_i].__contentRelativePath;
        ++_i;
    }
    
    array_sort(_nameArray, true); //Prettify the output a bit
    
    var _i = 0;
    repeat(array_length(_nameArray))
    {
        buffer_write(_buffer, buffer_text, "    ");
        buffer_write(_buffer, buffer_text, "\"");
        buffer_write(_buffer, buffer_text, _nameArray[_i]);
        buffer_write(_buffer, buffer_text, "\",\n");
        ++_i;
    }
    
    buffer_write(_buffer, buffer_text, "];\n");
    buffer_write(_buffer, buffer_text, "\n");
    
    
    
    //Then the variable expressions
    buffer_write(_buffer, buffer_text, "global.__dynamoVariableLookup = {\n");
    
    var _nameArray = variable_struct_get_names(global.__dynamoVariableLookup);
    array_sort(_nameArray, true); //Prettify the output a bit
    
    var _i = 0;
    repeat(array_length(_nameArray))
    {
        var _name  = _nameArray[_i];
        var _value = global.__dynamoVariableLookup[$ _name];
        
        //Sanitize!
        _name  = string_replace_all(_name,  "\"", "\\\"");
        _value = string_replace_all(_value, "\"", "\\\"");
        
        buffer_write(_buffer, buffer_text, "    ");
        buffer_write(_buffer, buffer_text, "\""); //We wrap the variable identifier in quote marks just in case a space sneaks in
        buffer_write(_buffer, buffer_text, _name);
        buffer_write(_buffer, buffer_text, "\": \"");
        buffer_write(_buffer, buffer_text, _value);
        buffer_write(_buffer, buffer_text, "\",\n");
        
        ++_i;
    }
    
    buffer_write(_buffer, buffer_text, "};");
    
    
    
    buffer_save(_buffer, _path);
    buffer_delete(_buffer);
    
    __DynamoTrace(array_length(global.__dynamoGMLArray), " GML files and ", variable_struct_names_count(global.__dynamoVariableLookup), " expressions were exported");
}